### ISSUE TITLE
не запускаеться script.js

### ISSUE THREAD

**Issue by ZyyyRu** [winlex/Script-for-SAM#1]
Привет при запуске script.js выдает ошибку вот [скриншот](http://img.zyyy.ru/i/dc9ab6de5c50710f717a01be44b1.png)

**Comment by winlex** [comment]
ты не правильно его запускаешь просто. я собирался как раз инструкцию сделать. я же только вчера скрипт выложил, а инструкцию не успел написать.

Смотри есть два способа:
1) Запустить как расширение для Chrome. сегодня кстати добавил такую штуку=)
2) открыть консоль в браузере на странице со значками. и вставить код со скрипта туда и энтер тыкнуть=) потом правой кнопочкой на консоль и сохранить лог. дальше перейти в папку с логом и изменить на *.bat  запустить)))

**Comment by ZyyyRu** [comment]
ок спасибо завтра буду пробовать

**Comment by ZyyyRu** [comment]
по второму способу запустил и в ответ получил код для запуска вот только не пойму зачем с 3 команды идет 215 раз повтор кода taskkill /f /im SAM.Game.exe
и после запуска полученого батника уже минут 5 висит на 2 строке ping -n 7200 127.0.0.1 > nul [скрин](http://img.zyyy.ru/i/d57fb45c72ea9dc8f038f7ba8c12.png) а также и сам полученый код из консоли [код](http://code.zyyy.ru/wvTitJ5J)
И да еще вопрос кога генерируешь код через браузер я как понимаю он забирает только то что показанно на данной странице?
тоесть если несколько страниц то процедуру нужно выполнять несколько раз?

**Comment by winlex** [comment]
> и после запуска полученого батника уже минут 5 висит на 2 строке ping -n 7200 127.0.0.1 > nul скрин 
Тебе надо выучить команды командной строки =))) это строка означает два часа задержки

> 215 раз повтор кода taskkill /f /im SAM.Game.exe
А вот за это спасибо. я чуть позже посмотрю что там накосячил я. ну а ты пожалуйста скинь скрипт который ты ввел. так как я проверял данный скрипт на двух вариантах профиля и все было ок))) я сейчас посмотрю что там, а ты пока скинь код скрипта. кстати сегодня утром придумал на рекурсию сделать, по моему мнению будет круче и оптимизированей)

**Comment by ZyyyRu** [comment]
вот этот [скрипт ](http://code.zyyy.ru/OPnnIfU9)я вводил в браузере firefox.
а игр уменя 1600+ вот [профиль](http://steamcommunity.com/id/zyyyru)
щас попробую твоим новым скриптом

**Comment by ZyyyRu** [comment]
Новый скрипт ток же выдал 215 таскилов подряд вод весь код всесте скриптом [код](http://code.zyyy.ru/J6tjGgmK)

**Comment by ZyyyRu** [comment]
Я так понимаю данными задержками твой скрипт имитирует проводимое время в игре?

**Comment by winlex** [comment]
> Новый скрипт ток же выдал 215 таскилов подряд вод весь код всесте скриптом код

ответ в твоем же ответе

> а игр уменя 1600+ вот профиль

у тебя много игр, и 215 игр требуют начального времени(2 часа)

> Я так понимаю данными задержками твой скрипт имитирует проводимое время в игре?

он создает батник имитирует SAM. путаница в этом значительная, ведь у меня нет авторских прав на SAM. так что точно надо говорить где мой скрипт работает а где прога

> Смотря на код я вижу что в данный момент лучше всего код выдает chrom в режиме расширения

странно но принципы одинаковые у них. ладно сейчас рекурсию доделаю и посмотрю что там не так когда просто вводишь.

**тему закрываю. решение найдено**

**Comment by winlex** [comment]
> Смотря на код я вижу что в данный момент лучше всего код выдает chrom в режиме расширения

проверил, все норм должно быть.у меня лично все работает
